name: kahoot
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  google_sign_in: ^6.1.4
  flutter:
    sdk: flutter
  geolocator: ^9.0.2  
  http: ^1.1.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/

